# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7k160tlfbv676-2L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/haoxi/Documents/Coding/verilog/ComputerOrganization/lab3_4/lab3_4.cache/wt [current_project]
set_property parent.project_path C:/Users/haoxi/Documents/Coding/verilog/ComputerOrganization/lab3_4/lab3_4.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/haoxi/Documents/Coding/verilog/ComputerOrganization/lab3_4/lab3_4.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files d:/Onedrive/Academic/ComputerOrganization/LAB/Exp03/coe/I9_mem.coe
add_files d:/Onedrive/Academic/ComputerOrganization/LAB/Exp03/coe/D_mem.coe
add_files -quiet C:/Users/haoxi/Documents/Coding/verilog/ComputerOrganization/lab3_4/lab3_4.srcs/sources_1/ip/RAM_B/RAM_B.dcp
set_property used_in_implementation false [get_files C:/Users/haoxi/Documents/Coding/verilog/ComputerOrganization/lab3_4/lab3_4.srcs/sources_1/ip/RAM_B/RAM_B.dcp]
add_files -quiet C:/Users/haoxi/Documents/Coding/verilog/ComputerOrganization/lab3_4/lab3_4.srcs/sources_1/ip/ROM_B/ROM_B.dcp
set_property used_in_implementation false [get_files C:/Users/haoxi/Documents/Coding/verilog/ComputerOrganization/lab3_4/lab3_4.srcs/sources_1/ip/ROM_B/ROM_B.dcp]
read_verilog -library xil_defaultlib {
  C:/Users/haoxi/Documents/Coding/verilog/ComputerOrganization/lab3_4/lab3_4.srcs/sources_1/imports/OExp02-7SEG/MUX8T1_8.v
  C:/Users/haoxi/Documents/Coding/verilog/ComputerOrganization/lab3_4/lab3_4.srcs/sources_1/imports/OExp02-7SEG/MUX8T1_32.v
  C:/Users/haoxi/Documents/Coding/verilog/ComputerOrganization/lab3_4/lab3_4.srcs/sources_1/imports/Port/SSeg7_Dev_IO.v
  C:/Users/haoxi/Documents/Coding/verilog/ComputerOrganization/lab3_4/lab3_4.srcs/sources_1/imports/Port/SPIO_IO.v
  C:/Users/haoxi/Documents/Coding/verilog/ComputerOrganization/lab3_4/lab3_4.srcs/sources_1/new/SCPU.v
  C:/Users/haoxi/Documents/Coding/verilog/ComputerOrganization/lab3_4/lab3_4.srcs/sources_1/new/Counter_x.v
  C:/Users/haoxi/Documents/Coding/verilog/ComputerOrganization/lab3_4/lab3_4.srcs/sources_1/imports/OExp02-7SEG/SAnti_jitter.v
  C:/Users/haoxi/Documents/Coding/verilog/ComputerOrganization/lab3_4/lab3_4.srcs/sources_1/imports/OExp02-7SEG/clk_div.v
  C:/Users/haoxi/Documents/Coding/verilog/ComputerOrganization/lab3_4/lab3_4.srcs/sources_1/imports/OExp02-7SEG/SEnter_2_32.v
  C:/Users/haoxi/Documents/Coding/verilog/ComputerOrganization/lab3_4/lab3_4.srcs/sources_1/imports/OExp02-7SEG/Multi_8CH32.v
  C:/Users/haoxi/Documents/Coding/verilog/ComputerOrganization/lab3_4/lab3_4.srcs/sources_1/imports/Port/MIO_BUS_IO.v
  C:/Users/haoxi/Documents/Coding/verilog/ComputerOrganization/lab3_4/lab3_4.srcs/sources_1/new/top.v
}
read_edif C:/Users/haoxi/Documents/Coding/verilog/ComputerOrganization/lab3_4/lab3_4.srcs/sources_1/imports/ngc/SPIO.ngc
read_edif C:/Users/haoxi/Documents/Coding/verilog/ComputerOrganization/lab3_4/lab3_4.srcs/sources_1/imports/ngc/SCPU.ngc
read_edif C:/Users/haoxi/Documents/Coding/verilog/ComputerOrganization/lab3_4/lab3_4.srcs/sources_1/imports/ngc/MIO_BUS.ngc
read_edif C:/Users/haoxi/Documents/Coding/verilog/ComputerOrganization/lab3_4/lab3_4.srcs/sources_1/imports/ngc/Counter_x.ngc
read_edif C:/Users/haoxi/Documents/Coding/verilog/ComputerOrganization/lab3_4/lab3_4.srcs/sources_1/imports/OExp02-7SEG/SAnti_jitter.ngc
read_edif C:/Users/haoxi/Documents/Coding/verilog/ComputerOrganization/lab3_4/lab3_4.srcs/sources_1/imports/OExp02-7SEG/SEnter_2_32.ngc
read_edif C:/Users/haoxi/Documents/Coding/verilog/ComputerOrganization/lab3_4/lab3_4.srcs/sources_1/imports/ngc/SSeg7_Dev.ngc
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/haoxi/Documents/Coding/verilog/ComputerOrganization/lab3_4/lab3_4.srcs/constrs_1/new/k7.xdc
set_property used_in_implementation false [get_files C:/Users/haoxi/Documents/Coding/verilog/ComputerOrganization/lab3_4/lab3_4.srcs/constrs_1/new/k7.xdc]


synth_design -top top -part xc7k160tlfbv676-2L


write_checkpoint -force -noxdef top.dcp

catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
