# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/haoxi/Documents/Coding/verilog/ComputerOrganization/lab3_4/lab3_4.srcs/sources_1/ip/ROM_B/ROM_B.xci
# IP: The module: 'ROM_B' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/haoxi/Documents/Coding/verilog/ComputerOrganization/lab3_4/lab3_4.srcs/sources_1/ip/ROM_B/ROM_B_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ROM_B'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: C:/Users/haoxi/Documents/Coding/verilog/ComputerOrganization/lab3_4/lab3_4.srcs/sources_1/ip/ROM_B/ROM_B.xci
# IP: The module: 'ROM_B' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/haoxi/Documents/Coding/verilog/ComputerOrganization/lab3_4/lab3_4.srcs/sources_1/ip/ROM_B/ROM_B_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ROM_B'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
