set_property SRC_FILE_INFO {cfile:C:/Users/haoxi/Documents/Coding/verilog/ComputerOrganization/lab3_4/lab3_4.srcs/constrs_1/new/k7.xdc rfile:../../../lab3_4.srcs/constrs_1/new/k7.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC AC18 IOSTANDARD LVCMOS18} [get_ports clk_100mhz]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC W13 IOSTANDARD LVCMOS18} [get_ports RSTN]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC M24 IOSTANDARD LVCMOS33} [get_ports seg_clk]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC M20 IOSTANDARD LVCMOS33} [get_ports seg_clrn]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC L24 IOSTANDARD LVCMOS33} [get_ports seg_sout]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC R18 IOSTANDARD LVCMOS33} [get_ports SEG_PEN]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC N26 IOSTANDARD LVCMOS33} [get_ports led_clk]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC N24 IOSTANDARD LVCMOS33} [get_ports led_clrn]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC M26 IOSTANDARD LVCMOS33} [get_ports led_sout]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC P18 IOSTANDARD LVCMOS33} [get_ports LED_PEN]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC V22 IOSTANDARD LVCMOS33} [get_ports CR]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC U22 IOSTANDARD LVCMOS33} [get_ports readn]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC U21 IOSTANDARD LVCMOS33} [get_ports RDY]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC V17 IOSTANDARD LVCMOS18} [get_ports BTN_x[0]]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC W18 IOSTANDARD LVCMOS18} [get_ports BTN_x[1]]
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC W19 IOSTANDARD LVCMOS18} [get_ports BTN_x[2]]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC W15 IOSTANDARD LVCMOS18} [get_ports BTN_x[3]]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC W16 IOSTANDARD  LVCMOS18}  [get_ports BTN_x[4]]
set_property src_info {type:XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC V18 IOSTANDARD  LVCMOS18}  [get_ports BTN_y[0]]
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC V19 IOSTANDARD  LVCMOS18}  [get_ports BTN_y[1]]
set_property src_info {type:XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC V14 IOSTANDARD LVCMOS18} [get_ports BTN_y[2]]
set_property src_info {type:XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC W14 IOSTANDARD  LVCMOS18} [get_ports BTN_y[3]]
set_property src_info {type:XDC file:1 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC AA10 IOSTANDARD LVCMOS15} [get_ports SW[0]]
set_property src_info {type:XDC file:1 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC AB10 IOSTANDARD LVCMOS15} [get_ports SW[1]]
set_property src_info {type:XDC file:1 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC AA13 IOSTANDARD LVCMOS15} [get_ports SW[2]]
set_property src_info {type:XDC file:1 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC AA12 IOSTANDARD LVCMOS15} [get_ports SW[3]]
set_property src_info {type:XDC file:1 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC Y13 IOSTANDARD LVCMOS15} [get_ports SW[4]]
set_property src_info {type:XDC file:1 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC Y12 IOSTANDARD LVCMOS15} [get_ports SW[5]]
set_property src_info {type:XDC file:1 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC AD11 IOSTANDARD LVCMOS15} [get_ports SW[6]]
set_property src_info {type:XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC AD10 IOSTANDARD LVCMOS15} [get_ports SW[7]]
set_property src_info {type:XDC file:1 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC AE10 IOSTANDARD LVCMOS15} [get_ports SW[8]]
set_property src_info {type:XDC file:1 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC AE12 IOSTANDARD LVCMOS15} [get_ports SW[9]]
set_property src_info {type:XDC file:1 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC AF12 IOSTANDARD LVCMOS15} [get_ports SW[10]]
set_property src_info {type:XDC file:1 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC AE8 IOSTANDARD LVCMOS15} [get_ports SW[11]]
set_property src_info {type:XDC file:1 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC AF8 IOSTANDARD LVCMOS15} [get_ports SW[12]]
set_property src_info {type:XDC file:1 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC AE13 IOSTANDARD LVCMOS15} [get_ports SW[13]]
set_property src_info {type:XDC file:1 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC AF13 IOSTANDARD LVCMOS15} [get_ports SW[14]]
set_property src_info {type:XDC file:1 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC AF10 IOSTANDARD LVCMOS15} [get_ports SW[15]]
set_property src_info {type:XDC file:1 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC AF24 IOSTANDARD LVCMOS33} [get_ports buzzer]
