# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7vx485tffg1157-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/haoxi/Documents/Coding/verilog/ComputerOrganization/single/single.cache/wt [current_project]
set_property parent.project_path C:/Users/haoxi/Documents/Coding/verilog/ComputerOrganization/single/single.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/haoxi/Documents/Coding/verilog/ComputerOrganization/single/single.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/haoxi/Documents/Coding/verilog/ComputerOrganization/single/single.srcs/sources_1/imports/OExp02-7SEG/MUX8T1_32.v
  C:/Users/haoxi/Documents/Coding/verilog/ComputerOrganization/single/single.srcs/sources_1/imports/Element/SignalExt_32.v
  C:/Users/haoxi/Documents/Coding/verilog/ComputerOrganization/single/single.srcs/sources_1/imports/Element/xor32.v
  C:/Users/haoxi/Documents/Coding/verilog/ComputerOrganization/single/single.srcs/sources_1/imports/Element/addc_32.v
  C:/Users/haoxi/Documents/Coding/verilog/ComputerOrganization/single/single.srcs/sources_1/imports/Element/nor32.v
  C:/Users/haoxi/Documents/Coding/verilog/ComputerOrganization/single/single.srcs/sources_1/imports/Element/and32.v
  C:/Users/haoxi/Documents/Coding/verilog/ComputerOrganization/single/single.srcs/sources_1/imports/Element/or32.v
  C:/Users/haoxi/Documents/Coding/verilog/ComputerOrganization/single/single.srcs/sources_1/imports/Element/srl32.v
  C:/Users/haoxi/Documents/Coding/verilog/ComputerOrganization/single/single.srcs/sources_1/new/sign_ext.v
  C:/Users/haoxi/Documents/Coding/verilog/ComputerOrganization/single/single.srcs/sources_1/imports/new/regs.v
  C:/Users/haoxi/Documents/Coding/verilog/ComputerOrganization/single/single.srcs/sources_1/imports/new/ALU.v
  C:/Users/haoxi/Documents/Coding/verilog/ComputerOrganization/single/single.srcs/sources_1/new/scpu_ctrl.v
  C:/Users/haoxi/Documents/Coding/verilog/ComputerOrganization/single/single.srcs/sources_1/new/data_path.v
  C:/Users/haoxi/Documents/Coding/verilog/ComputerOrganization/single/single.srcs/sources_1/new/cpu.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top cpu -part xc7vx485tffg1157-1


write_checkpoint -force -noxdef cpu.dcp

catch { report_utilization -file cpu_utilization_synth.rpt -pb cpu_utilization_synth.pb }
